name: DEV CI

on:
  push:
    branches:
      - 'dev'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Install Dependencies
        run: npm ci
      # SAFE
      - name: Build doc Shared Library
        run: npm run compodoc:safe
      - name: Archive build Shared Library
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: doc_safe
          path: documentation/safe
      # BACK-OFFICE
      # - name: Build doc Back-office
      #   run: npm run compodoc:back
      # - name: Archive build Back-office
      #   if: success()
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: doc_back_office
      #     path: documentation/back-office
      # FRONT-OFFICE 
      # - name: Build doc Front-office
      #   run: npm run compodoc:front
      # - name: Archive build Front-office
      #   if: success()
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: doc_front_office
      #     path: documentation/front-office

  deploy_safe_documentation:
    name : Deploy @SAFE documentation 🚀
    runs-on: ubuntu-latest
    needs: build
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download doc
        uses: actions/download-artifact@v1
        with:
          name: doc_safe
          path: documentation/safe
      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          token: ${{ secrets.COMPODOC_GITHUB_PAGES_TOKEN }}
          repository-name: ReliefApplications/ReliefApplications.github.io
          branch: master
          folder: doc_safe
          target-folder: emrs-safe-frontend/@safe
          clean: true
