name: Node.js CD

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build and Test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name:
      run: npm ci
    - name: Build Shared Library
      run: npm run build:ci who-ems
    - name: Build
      run: npm run build:ci
    - name: Test
      run: npm run test:ci