name: Front-end CD

on:
  push:
    branches:
      - 'stage'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm ci
    - name: Build Shared Library
      run: npm run build -- --prod safe
    - name: Build RA Back-office
      run: npm run build:ci:ra
    - name: Build RA Front-office
      run: npm run build:ci:ra -- --project=front-office
    - name: Archive build RA Back-office
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: deploy_dist_back_office
        path: dist/back-office
    - name: Archive build RA Front-office
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: deploy_dist_front_office
        path: dist/front-office

  deploy_stage_back_office:
    name: Deploy STAGE Back-office 🚀
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download build
      uses: actions/download-artifact@v1
      with:
        name: deploy_dist_back_office
        path: dist/back-office
    - name: Setup SSH Keys and known_hosts
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_SAFE_PRIVATE_KEY }}
    - name: Deploy
      run: ./CI/deploy-back-office.sh
      env:
        SSH_PASS: ${{ secrets.SSH_SAFE_PASS }}

  deploy_stage_front_office:
    name: Deploy STAGE Front-office 🚀
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download build
      uses: actions/download-artifact@v1
      with:
        name: deploy_dist_front_office
        path: dist/front-office
    - name: Setup SSH Keys and known_hosts
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_SAFE_PRIVATE_KEY }}
    - name: Deploy
      run: ./CI/deploy-front-office.sh
      env:
        SSH_PASS: ${{ secrets.SSH_SAFE_PASS }}
